### ISSUE TITLE
Menu-less launch options

### ISSUE THREAD

**Issue by hackern0v1c3** [trustedsec/hate_crack#17]
It would make it easier to use hate_crack with other scripts if there were options to run cracking without interacting with the main menu.  An example would be

sudo python /opt/hatecrack/hate_crack.py ~/Documents/example_ntlm.txt 1000 1 0

Which would run quick cracking with 0 best64.rule.  I'm not at all suggesting that you get rid of the main menu, just providing both launch options would be a really nice feature.

Keep up the fantastic work!

**Comment by bandrel** [comment]
The quick crack with 0 has been fixed in the lastest version just pushed.  I'll get the new feature request working shortly

**Comment by hackern0v1c3** [comment]
Wow didn't expect such a quick reply.  You guys are great.

**Comment by braimee** [comment]
Just adding a "me too" to this request as I have a situation where I'm doing some cracking on a box where I want to add `--gpu-temp-disable` and do a quick crack (or other jobs) and still use HateCrack, and not sure I can do it with the current menu configuration.  Is there any "hack" I can do in the meantime to work around this?  

(And sorry if I'm hijacking this thread, I can happily start a new one if need be. Don't punch me @hackern0v1c3 :-) )

**Comment by bandrel** [comment]
@hackern0v1c3 might be a while before we can get this implemented, but @braimee good news you can already do what you need to do by editing the tuning field of the config.
From
`"hcatTuning": "--force"` 
to 
`"hcatTuning": "--force --gpu-temp-disable"`

**Comment by braimee** [comment]
Rockin'!  Thanks @bandrel !

**Comment by braimee** [comment]
*Cough* @hackern0v1c3 ;-)

**Comment by hackern0v1c3** [comment]
I just tossed a quick and dirty pull request at you.  Let me know if the approach at least seems reasonable.  I can expand on it if people find it valuable.  Or feel free to tell me to take my newb python and beat it 👍

**Comment by bandrel** [comment]
After discussing this with the team the whole purpose of hate_crack is to be menu driven so we're not going to be moving forward with any additional command line arguments other than what is currently present.
