### ISSUE TITLE
Any chance of a Windows Python port for us poor folks stuck on a Windows base platform?

### ISSUE THREAD

**Issue by SSATKINS** [trustedsec/hate_crack#19]
Pretty please?

:-)

Yours Hopefully,
SS.

**Comment by bandrel** [comment]
Some of the functionality uses built in linux commands like grep/cut etc. I'll have to see if I can easily port them to pure python so that we can make it Windows compatible.

**Comment by bandrel** [comment]
I tried to make it portable, but there were some issues with the way that PACK was written that would make it so we can directly import it in to python like we should be able to so thats why we are calling it as a subprocess. The nail in the coffin however is the sort -u that takes place twice. Using the sort utility is much more efficient than doing the sorting in python so I'm afraid that the performance loss would not make it a viable choice for large lists.
