### ISSUE TITLE
Recommended methodology?

### ISSUE THREAD

**Issue by braimee** [trustedsec/hate_crack#20]
Hi there,

This isn't really an issue, but more a question about best practices for using Hatecrack.  Do you have a recommended methodology for which Hatecrack options to use to most efficiently crack a list of hashes.  I've just been starting at 1 and going up from there, and if there's a certain option that says it'll take days to run, I maybe let it run 24 hours and go on to the next for the sake of time.  

But I'd love to hear if this is how the TrustedSec team uses the tool or if you have other recommendations/tips.

Thanks for the great tool!

Brian

**Comment by Spoonman1091** [comment]
Hey @braimee, sorry for the late response. The script is our methodology, or rather many people's methodologies bundled up for easy access. Each option will likely crack passwords that another may not. It's just a matter of how much time you have and how much hardware juice you have. Start with a "Quick Crack" and move your way down the list. Also, the README has more details on what each option performs.

**Comment by braimee** [comment]
Ok thanks much!
