### ISSUE TITLE
Check if destination folder exists

### ISSUE THREAD

**Issue by voidnecron** [trustedsec/hate_crack#29]
Hi,

Simple request: a check if the destination folder exists, and if not let wordlist_optimizer.py create it or complain about missing permissions to do so?
At the moment it spits out this:
> $ python wordlist_optimizer.py /usr/share/wordlists/rockyou.txt /usr/share/wordlists/optimized_wordlists/
> 123456
> Traceback (most recent call last):
>   File "wordlist_optimizer.py", line 74, in <module>
>     main()
>   File "wordlist_optimizer.py", line 45, in main
>     if len(os.listdir(destination)) == 0:
> OSError: [Errno 2] No such file or directory: '/usr/share/wordlists/optimized_wordlists/'

Cheers!

**Comment by bandrel** [comment]
try this branch and let me know if you have any issues. If you have none I'll merge into master. https://github.com/trustedsec/hate_crack/tree/wordlist_optimizer
