### ISSUE TITLE
wordlist_optimizer choking on certain wordlists?

### ISSUE THREAD

**Issue by braimee** [trustedsec/hate_crack#32]
Hello,

I just spun up a fresh Linux box, downloaded hashcat + utils + hatecrack as well as a bundle of wordlists, and am ready to run wordlist_optimizer.

As I kick off the optimization, I'll see hatecrack kind of bomb out with a blurb of text like this:

````
Checking /opt/wordlists/optimized//58 against cache
Lines compared 18
Removed 12 lines from cache

Sorting back to original positions...

Finished!
Removed 12 lines from cache
Writing 238119 lines to /tmp/splitlen.out
Traceback (most recent call last):
  File "wordlist_optimizer.py", line 88, in <module>
    main()
  File "wordlist_optimizer.py", line 72, in main
    if lineCount("/tmp/splitlen.out") > 0:
  File "wordlist_optimizer.py", line 20, in lineCount
    for line in outFile:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1239: invalid start byte
````

Note: the issue appears to be wordlist related.  This was happening on `crackstation.txt`.  I renamed it to `crackstation2.txt` and then optimizer completed.  Anything I can do to help troubleshoot why certain wordlists might be problematic?  I'd love to have crackstation (and a few others that bomb out too) get properly optimized.

Thanks,
Brian

**Comment by bandrel** [comment]
To be honest the wordlist optimization script isn't entirely necessary any longer with modern hashcat. It is however still a helpful way to deduplicate and merge new wordlists in with old ones.
