### ISSUE TITLE
Add pipal menu option

### ISSUE THREAD

**Issue by discoking** [trustedsec/hate_crack#33]
If I added [pipal](https://github.com/digininja/pipal)  as a menu option is this something you would be interested in accepting a pull request for?

I would add it as as an option in the config, and if it was disabled then the menu wouldn't show up

**Comment by Spoonman1091** [comment]
I like it! You will have to pull out all of the HEX results and convert them first.

**Comment by bandrel** [comment]
merged in https://github.com/trustedsec/hate_crack/pull/35
