### ISSUE TITLE
Invalid Path for hashcat binary

### ISSUE THREAD

**Issue by barrett092** [trustedsec/hate_crack#8]
Getting this error even though I'm pretty sure the config.json file is pointing to the right folder paths....

**Comment by bandrel** [comment]
can you submit any errors that you are getting.  Also can you upload the full path of the bin and a copy of the config.json file?  If you'd prefer to encrypt that data here is my public key https://keybase.io/bandrel/pgp_keys.asc

**Comment by barrett092** [comment]
i ended up fixing it, it was a syntax error on my end, sorry about that
